// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Aleksey Fishchev",
            "email": "mrfishchev@seniorvlogger.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/MrFishchev/godtop/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/container/{nameOrId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves container information by its Id or Name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "container Name or Id",
                        "name": "nameOrId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Container"
                        }
                    }
                }
            }
        },
        "/container/{nameOrId}/stats": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves statistics of a container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "container Name or Id",
                        "name": "nameOrId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ContainerStats"
                        }
                    }
                }
            }
        },
        "/containers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves running containers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Container"
                            }
                        }
                    }
                }
            }
        },
        "/host": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves information about host stystem",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.HostInfo"
                        }
                    }
                }
            }
        },
        "/volumes": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves mounted and created volumes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Volume"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Container": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "publicPorts": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "state": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "domain.ContainerStats": {
            "type": "object",
            "properties": {
                "cpuUsage": {
                    "type": "number"
                },
                "memoryUsage": {
                    "type": "number"
                },
                "rxBytes": {
                    "type": "integer"
                },
                "txBytes": {
                    "type": "integer"
                },
                "usedMemory": {
                    "type": "integer"
                }
            }
        },
        "domain.HostInfo": {
            "type": "object",
            "properties": {
                "cpuUsage": {
                    "type": "number"
                },
                "totalMemory": {
                    "type": "integer"
                },
                "totalStorage": {
                    "type": "integer"
                },
                "totalSwapMemory": {
                    "type": "integer"
                },
                "usedMemory": {
                    "type": "integer"
                },
                "usedStorage": {
                    "type": "integer"
                },
                "usedSwapMemory": {
                    "type": "integer"
                }
            }
        },
        "domain.Volume": {
            "type": "object",
            "properties": {
                "destination": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/api",
	Schemes:     []string{},
	Title:       "Godtop",
	Description: "Docker graphical activity monitor",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
